import { ShieldCheck } from "lucide-react";

export function ResponsibleAiNotice({ compact = false }: { compact?: boolean }) {
  return (
    <div className="rounded-lg border border-border/70 bg-secondary/40 p-3 text-xs text-muted-foreground">
      <p className="flex items-center gap-2 font-medium text-foreground">
        <ShieldCheck className="size-3.5 text-accent" aria-hidden />
        Responsible AI
      </p>
      <p className="mt-1.5 leading-relaxed">
        {compact
          ? "AI outputs can be inaccurate or biased. Review and edit before sharing, and never paste confidential data."
          : "Outputs are generated by AI and may be inaccurate, incomplete or biased. Always review, edit and fact-check before sending or acting on them. Avoid entering confidential, personal or regulated information, and keep a human accountable for every final decision."}
      </p>
    </div>
  );
}